/*jslint node: true */

module.exports = {
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    INCREASE_ITEM: 'INCREASE_ITEM',
    DECREASE_ITEM: 'DECREASE_ITEM',

    SELECT_AUDIO: 'SELECT_AUDIO',
    SELECT_SUBSCRIPTIONS: 'SELECT_SUBSCRIPTIONS',
    REFRESH_SUBSCRIPTIONS: 'REFRESH_SUBSCRIPTIONS',
    ADD_SUBSCRIPTION: 'ADD_SUBSCRIPTION',
    REMOVE_SUBSCRIPTION: 'REMOVE_SUBSCRIPTION',
    UPDATE_SUBSCRIPTION_INFO: 'UPDATE_SUBSCRIPTION_INFO'
};