/*jslint node: true */

module.exports = {
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    INCREASE_ITEM: 'INCREASE_ITEM',
    DECREASE_ITEM: 'DECREASE_ITEM',

    SELECT_AUDIO: 'SELECT_AUDIO',
    SELECT_SUBSCRIPTIONS: 'SELECT_SUBSCRIPTIONS',
    RELOAD_SUBSCRIPTIONS: 'RELOAD_SUBSCRIPTIONS',
    REFRESH_SUBSCRIPTIONS: 'REFRESH_SUBSCRIPTIONS',
    ADD_SUBSCRIPTION: 'ADD_SUBSCRIPTION',
    REMOVE_SUBSCRIPTION: 'REMOVE_SUBSCRIPTION',
    UPDATE_SUBSCRIPTION_INFO: 'UPDATE_SUBSCRIPTION_INFO',

    PODCAST_SELECT_AUDIO: 'PODCAST_SELECT_AUDIO',

    PLAYER_PLAY: 'PLAYER_PLAY',
    PLAYER_PAUSE: 'PLAYER_PAUSE',
    PLAYER_SET_TIME: 'PLAYER_SET_TIME',
    PLAYER_SET_TIME_REPLAY: 'PLAYER_SET_TIME_REPLAY',
    PLAYER_SET_TIME_FORWARD: 'PLAYER_SET_TIME_FORWARD',
    PLAYER_SET_VOLUME: 'PLAYER_SET_VOLUME',
    PLAYER_SET_PLAYBACK_RATE: 'PLAYER_SET_PLAYBACK_RATE',
    PLAYER_TOOGLE_CAST: 'PLAYER_TOOGLE_CAST'
};